# Generated by Django 3.2.6 on 2021-08-12 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from expensetracker.settings import categories, currencies


def start_categories(apps, schema_editor):
    Category = apps.get_model('expenses', 'Category')
    for category in categories:
        Category(name=category).save()


def start_currencies(apps, schema_editor):
    Currency = apps.get_model('expenses', 'Currency')
    for country, shortcut in currencies.items():
        Currency(shortcut=shortcut, country=country).save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(max_length=5, unique=True)),
                ('country', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('type', models.CharField(choices=[
                 ('E', 'Expence'), ('I', 'Income')], default='E', max_length=1)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(blank=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='expenses.category')),
                ('currency', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='expenses.currency')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateField(auto_now_add=True)),
                ('currency', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='expenses.currency')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(start_categories),
        migrations.RunPython(start_currencies),

    ]
